# Generated by Django 3.2.5 on 2021-07-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SorteioMegaSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dezena1', models.PositiveSmallIntegerField()),
                ('dezena2', models.PositiveSmallIntegerField()),
                ('dezena3', models.PositiveSmallIntegerField()),
                ('dezena4', models.PositiveSmallIntegerField()),
                ('dezena5', models.PositiveSmallIntegerField()),
                ('dezena6', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
