# Generated by Django 3.2.5 on 2021-07-18 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('megasena', '0002_alter_sorteiomegasena_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dezena1', models.PositiveSmallIntegerField()),
                ('dezena2', models.PositiveSmallIntegerField()),
                ('dezena3', models.PositiveSmallIntegerField()),
                ('dezena4', models.PositiveSmallIntegerField()),
                ('dezena5', models.PositiveSmallIntegerField()),
                ('dezena6', models.PositiveSmallIntegerField()),
                ('dezena7', models.PositiveSmallIntegerField(null=True)),
                ('dezena8', models.PositiveSmallIntegerField(null=True)),
                ('dezena9', models.PositiveSmallIntegerField(null=True)),
                ('dezena10', models.PositiveSmallIntegerField(null=True)),
                ('dezenas', models.PositiveSmallIntegerField(choices=[(1, '1 dezena(s)'), (2, '2 dezena(s)'), (3, '3 dezena(s)'), (4, '4 dezena(s)'), (5, '5 dezena(s)'), (6, '6 dezena(s)'), (7, '7 dezena(s)'), (8, '8 dezena(s)'), (9, '9 dezena(s)'), (10, '10 dezena(s)')])),
                ('acertos', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
