# Generated by Django 3.2.5 on 2021-07-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megasena', '0003_novojogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novojogo',
            name='dezenas',
            field=models.PositiveSmallIntegerField(choices=[(6, '6 dezena(s)'), (7, '7 dezena(s)'), (8, '8 dezena(s)'), (9, '9 dezena(s)'), (10, '10 dezena(s)')]),
        ),
    ]
